name: Build Client
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      # Only when changes to either a cpp or h file.
      - 'src/benternet_client/*.cpp'
      - 'src/benternet_client/*.h'
# Dont keep running when a new build is in progress
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build libzmq & cppzmq
      run: |
        mkdir libs && cd libs
        git clone https://github.com/zeromq/libzmq.git && git clone https://github.com/zeromq/cppzmq.git
        cd libzmq
        mkdir build
        cd build
        cmake ..
        sudo make -j4 install
        cd ../../
        cd cppzmq
        mkdir build
        cd build
        cmake ..
        sudo make -j4 install
        cd
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        host:         linux
        target:       desktop
        setup-python: false
    - name: Run qmake
      run: |
        mkdir src/build && cd src/build
        qmake -o Makefile ../benternet_client/benternet_client.pro
    - name: Run make
      run: cd src/build && make
    - name: create appimage
      uses: AppImageCrafters/build-appimage@master
      with:
        recipe: "./appimage-demo-qt5/AppImageBuilder.yml"
      env:
        UPDATE_INFO: gh-releases-zsync|AppImageCrafters|appimage-demo-qt5|latest|*x86_64.AppImage.zsync
    - uses: actions/upload-artifact@v3
      with:
        name: benternet_client
