name: Build Client
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      # Only when changes to either a cpp or h file.
      - 'src/benternet_client/*.cpp'
      - 'src/benternet_client/*.h'
# Dont keep running when a new build is in progress
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y qtbase5-dev libzmq3-dev

    - name: Build project
      run: qmake && make

    - name: Create release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0
        release_name: Release 1.0
        body: |
          This is the first release.
        draft: false
        prerelease: false

    - name: Upload binary
      uses: actions/upload-release-asset@v1
      with:
        asset_path: ./build/project
        asset_name: project
        asset_content_type: application/octet-stream
